#!/usr/bin/env bash
set -e

mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install -Dquarkus.version=${QUARKUS_VERSION} -Dversion.io.quarkus=${QUARKUS_VERSION} -Dnative -Dquarkus.native.container-build=true
