= quarkus-ecosystem-ci
:plantuml: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/quarkusio/quarkus-ecosystem-ci/master/

Repository used for orchestrating cross-CI builds of extensions part of Quarkus ecosystem/universe.

== What it's all about

It's in everyone's interest to know if Quarkus extensions and especially participants in the [Quarkus Platform](https://github.com/quarkusio/quarkus-platform) build properly 
against the latest Quarkus, since Quarkus moves very fast.
At the same time, due to resource constraints it is not possible for every extension to run their tests in the Quarkus organization.
In that vein Quarkus has come up with a solution that allows both Quarkus members and Quarkus Platform participants to know each day whether their extension
works with the latest Quarkus or not, while sharing the CI load amongst platform participants.
Furthermore, the solution aims to be as frictionless as possible for Quarkus Platform participants while also not requiring said participants to trust 
Quarkus with their GitHub tokens. 

This repository contains the metadata that needs to be setup for a platform participant to have their CI automatically triggered and post the result on a Quarkus issue.

image::{plantuml}/ci-overview.puml[CI Overview]

== What do I need to do as a Quarkus Platform participant  

After your extension has been added to the Quarkus Platform, you will additionally need to do the following:

1. Open an issue on the Quarkus repo, where updates will be posted (the CI job will close or open the issue depending on the CI outcome). 
An example of such an issue is can be found https://github.com/quarkusio/quarkus/issues/8593[here].
+
Note that in one of the following steps you will need to configure a Github token for **this** user in **your** extension repository. 
The user can be a regular user (for example the author of the extension) or a bot.   

2. Open a Pull Request to this https://github.com/quarkusio/quarkus-ecosystem-ci[quarkus-ecosystem-ci] repository where you add a directory for your extension and inside it place a file named `info.yaml`.
+
The needs to contain the following information:
+
[source,yaml]
----
url: https://github.com/someorg/my-extension # Github repo of your extension
issues:
  repo: quarkusio/quarkus # this should be left as is when CI updates are going to be reported on the Quarkus repository
  latestCommit: 123456 # this is the number of the issue you created above
----
+
An example of the above configuration can be found https://github.com/quarkusio/quarkus-ecosystem-ci/blob/419a6c18312ac26ab0213ae1bf0ee6d38a550f4e/qpid/info.yaml[here].

3. Add a secret named `ECOSYSTEM_CI_TOKEN` in your repository that contains the token of the user that opened the issue mentioned in the first step. This token will be used
in order to open and close the issue from the CI action.

4. Add the following file to configure the Quarkus CI in Github Actions for your repository:
+
`.github/workflows/quarkus-snapshot.yaml` (this file contains the actual Github Actions declaration)
+
[source,yaml]
----
name: "Quarkus ecosystem CI"
on:
  watch:
    types: [started]

# For this CI to work, ECOSYSTEM_CI_TOKEN needs to contain a GitHub with rights to close the Quarkus issue that the user/bot has opened,
 # while 'ECOSYSTEM_CI_REPO_PATH' needs to be set to the corresponding path in the 'quarkusio/quarkus-ecosystem-ci' repository

env:
  ECOSYSTEM_CI_REPO: quarkusio/quarkus-ecosystem-ci
  ECOSYSTEM_CI_REPO_FILE: context.yaml
  JAVA_VERSION: 11

  #########################
  # Repo specific setting #
  #########################

  ECOSYSTEM_CI_REPO_PATH: FIXME # TODO: this needs to be set to the directory name added in 'quarkusio/quarkus-ecosystem-ci'

jobs:
  build:
    name: "Build against latest Quarkus snapshot"
    runs-on: ubuntu-latest
    if: github.actor == 'quarkusbot'

    steps:
      - name: Install yq
        run: sudo add-apt-repository ppa:rmescandon/yq && sudo apt update && sudo apt install yq -y

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: current-repo
          ref: master

      - name: Checkout Ecosystem
        uses: actions/checkout@v2
        with:
          repository: ${{ env.ECOSYSTEM_CI_REPO }}
          ref: master
          path: ecosystem-ci

      - name: Setup and Run Tests
        run: ./ecosystem-ci/setup-and-test
        env:
          ECOSYSTEM_CI_TOKEN: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
----

Finally, if your extension requires a custom test script (by default `quarkus-ecosystem-test` from this repository is used), add a file named `.github/quarkus-ecosystem-test`.

Example projects containing the proper Github Action YAML file (and which has been tested with the whole process) can be found https://github.com/geoand/quarkus-qpid-jms/blob/51a03f41c38ea43dedf05c25e2277dbf99d88d50/.github[here] and https://github.com/quarkusio/quarkus-platform/tree/master/.github[here].

== How come this works?

The "trick" (more like a hack actually) is that Quarkus Platform participant's Github Actions are triggered when the Quarkus Ecosystem CI stars the extension repository.
Furthermore, before starring the repository, some context information is written to this repository which is then meant to be read in the triggered Github Action.
This way this Quarkus Github Action does not need to hold any secrets for the participants.  
