#!/usr/bin/env bash
set -e

cd ecosystem-ci/${ECOSYSTEM_CI_REPO_PATH}
# if an alternative is not specified, then we just read the global info
if [[ -z "${ALTERNATIVE}" ]]; then
  ISSUE_NUM=$(yq r ${ECOSYSTEM_CI_REPO_FILE} issues.latestCommit)
  QUARKUS_SHA=$(yq r ${ECOSYSTEM_CI_REPO_FILE} quarkus.sha)
else
  ISSUE_NUM=$(yq r ${ECOSYSTEM_CI_REPO_FILE} alternatives.${ALTERNATIVE}.issue)
  QUARKUS_BRANCH=$(yq r ${ECOSYSTEM_CI_REPO_FILE} alternatives.${ALTERNATIVE}.quarkusBranch)
fi
# we assume that the issue repository doesn't change between alternatives
ISSUE_REPO=$(yq r ${ECOSYSTEM_CI_REPO_FILE} issues.repo)
# we assume that this version correct no matter what Quarkus source we checkout
QUARKUS_VERSION=$(yq r ${ECOSYSTEM_CI_REPO_FILE} quarkus.version)
cd - > /dev/null

# Checkout Quarkus
if [[ -z "${QUARKUS_BRANCH}" ]]; then
  # a depth of 1 should be fine because this runs almost as soon as the original value of QUARKUS_SHA was created,
  # but lets be on the safe side by pulling in some more history
  git clone --depth=20 --branch master https://github.com/quarkusio/quarkus.git
  cd quarkus
  git checkout ${QUARKUS_SHA}
else
  # if a branch was specified, then just check that out
  git clone --depth=1 --branch ${QUARKUS_BRANCH} https://github.com/quarkusio/quarkus.git
  cd quarkus
fi

# Build Quarkus
./mvnw -B clean install -DskipTests -DskipITs -DskipDocs

cd - > /dev/null

# delete the quarkus repository in order to allow multiple consecutive executions of this script
rm -rf quarkus

cd current-repo

# check the test script
if [ -f .github/quarkus-ecosystem-test ]; then
    echo "Test script found"
else
    echo "Test script not found - using default from quarkus-ecosystem-ci"
    cp ../ecosystem-ci/quarkus-ecosystem-test .github/quarkus-ecosystem-test
fi

# check the report script
if [ -f .github/quarkus-ecosystem-issue.java ]; then
    echo "Report script found"
else
    echo "Report script not found - using default from quarkus-ecosystem-ci"
    cp ../ecosystem-ci/quarkus-ecosystem-issue.java .github/quarkus-ecosystem-issue.java
fi

# check the Maven settings file
if [ -f .github/quarkus-ecosystem-maven-settings.xml ]; then
    echo "Maven settings file found"
else
    echo "Maven settings file not found - using default from quarkus-ecosystem-ci"
    cp ../ecosystem-ci/quarkus-ecosystem-maven-settings.xml .github/quarkus-ecosystem-maven-settings.xml
fi

# perform actual test run
if QUARKUS_VERSION=${QUARKUS_VERSION} .github/quarkus-ecosystem-test ; then
  echo "Tests succeeded"
  TEST_STATUS="success"
else
  echo "Tests failed"
  TEST_STATUS="failure"
fi

echo "Attempting to report results"

sudo apt-get update -o Dir::Etc::sourcelist="sources.list" \
  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
sudo apt-get install -y gnupg2 gnupg-agent
echo "Installing SDKMAN"
curl -s "https://get.sdkman.io" | bash
source ~/.sdkman/bin/sdkman-init.sh
sed -i -e 's/sdkman_auto_answer=false/sdkman_auto_answer=true/g' ~/.sdkman/etc/config
sdk install jbang 0.50.1

jbang .github/quarkus-ecosystem-issue.java token="${ECOSYSTEM_CI_TOKEN}" status="${TEST_STATUS}" issueRepo="${ISSUE_REPO}" issueNumber="${ISSUE_NUM}" thisRepo="${GITHUB_REPOSITORY}" runId="${GITHUB_RUN_ID}"

echo "Report completed"

if [[ ${TEST_STATUS} != "success" ]]; then
  exit 1
fi
